"use client";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useArtwork,useArtworks } from "@/hooks/useQueries";
import { useCartStore } from "@/store/cart";
import { ArrowLeft,ShoppingBag } from "lucide-react";
import { toast } from "sonner";
export default function ProductPage(){const params=useParams<{id:string}>();const id=Number(params.id);const{data:artwork,isLoading,isError}=useArtwork(id);const{data:artworks=[],isLoading:loading}=useArtworks();const add=useCartStore(s=>s.addItem);const related=artworks.filter(a=>a.id!==id).slice(0,3);
if(isLoading)return <div className="mx-auto max-w-6xl px-6 py-12 grid gap-10 lg:grid-cols-2"><Skeleton className="aspect-[4/5]"/><div className="flex flex-col justify-center gap-4"><Skeleton className="h-10 w-3/4"/><Skeleton className="h-6 w-32"/><Skeleton className="h-24 w-full"/></div></div>;
if(isError||!artwork)return <div className="mx-auto max-w-6xl px-6 py-24 text-center"><h1 className="font-display text-3xl">Artwork not found</h1><Button asChild className="mt-8"><Link href="/shop"><ArrowLeft className="size-4"/>Back to shop</Link></Button></div>;
return <div className="mx-auto max-w-6xl px-6 py-12"><Link href="/shop" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Back to shop</Link><div className="mt-8 grid gap-10 lg:grid-cols-2 lg:gap-16"><div className="overflow-hidden rounded-lg border bg-card shadow-subtle"><img src={artwork.imageUrl} alt={artwork.title} className="aspect-[4/5] w-full object-cover"/></div><div className="flex flex-col justify-center">{artwork.featured&&<span className="mb-4 inline-flex w-fit rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-primary">Featured</span>}<h1 className="font-display text-4xl font-medium leading-tight sm:text-5xl">{artwork.title}</h1><p className="mt-4 font-display text-2xl font-medium text-primary">{format(artwork.price)}</p><p className="mt-6 max-w-prose leading-relaxed text-muted-foreground">{artwork.description}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" onClick={()=>{add(id);toast.success("Added to cart")}}><ShoppingBag className="size-4"/>Add to cart</Button><Button asChild size="lg" variant="outline"><Link href="/cart">View cart</Link></Button></div></div></div>
<section className="mt-20"><div className="flex items-end justify-between"><h2 className="font-display text-2xl font-medium">More from the collection</h2><Link href="/shop" className="text-sm text-muted-foreground">View all</Link></div>{loading?<div className="mt-6 grid grid-cols-2 gap-6 sm:grid-cols-3">{["a","b","c"].map(k=><Skeleton key={k} className="aspect-[4/5]"/>)}</div>:<div className="mt-6 grid grid-cols-2 gap-6 sm:grid-cols-3">{related.map(item=><Link key={item.id} href={`/artwork/${item.id}`} className="group overflow-hidden rounded-lg border bg-card"><img src={item.imageUrl} alt={item.title} className="aspect-[4/5] w-full object-cover transition-transform duration-300 group-hover:scale-105"/><div className="p-4"><h3 className="truncate font-display text-lg">{item.title}</h3><p className="mt-1 text-sm font-medium text-primary">{format(item.price)}</p></div></Link>)}</div>}</section></div>}
function format(c:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100)}
