-- Run this entire file once in Supabase Dashboard > SQL Editor.
create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  title text not null,
  price integer not null,
  description text not null default '',
  image_url text not null,
  image_path text,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  stripe_session_id text unique,
  email text,
  customer_name text,
  total integer not null,
  currency text not null default 'usd',
  status text not null default 'PENDING' check (status in ('PENDING','PAID','FAILED')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  artwork_id bigint not null references public.artworks(id),
  title text not null,
  price integer not null,
  quantity integer not null
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  type text not null,
  artwork_id bigint references public.artworks(id) on delete set null,
  path text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do update set public = true;

alter table public.artworks enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.analytics_events enable row level security;

-- The app uses the server-side Supabase service-role key, so it bypasses these policies.
-- Public users do not get direct database access.
