"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect,useState } from "react";
import { useArtworks } from "@/hooks/useQueries";
import { useCartStore } from "@/store/cart";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ArrowLeft,CheckCircle2,Minus,Plus,ShoppingBag,Trash2 } from "lucide-react";
import { toast } from "sonner";
export default function CartPage(){
 const {data:artworks=[],isLoading}=useArtworks();const lines=useCartStore(s=>s.items);const update=useCartStore(s=>s.updateItem);const remove=useCartStore(s=>s.removeItem);const clear=useCartStore(s=>s.clear);const search=useSearchParams();const[complete,setComplete]=useState(false);const[loading,setLoading]=useState(false);
 useEffect(()=>{const sid=search.get("session_id");if(sid){setComplete(true);clear();}},[search,clear]);
 const map=new Map(artworks.map(a=>[a.id,a]));const items=lines.map(line=>({line,artwork:map.get(line.artworkId)})).filter(x=>x.artwork);const subtotal=items.reduce((s,x)=>s+(x.artwork!.price*x.line.quantity),0);
 if(complete)return <div className="mx-auto max-w-2xl px-6 py-24 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-primary/10 text-primary"><CheckCircle2 className="size-8"/></div><h1 className="mt-6 font-display text-4xl">Thank you for your order</h1><p className="mx-auto mt-4 max-w-md text-muted-foreground">Your payment was successful and your order has been recorded.</p><Button asChild className="mt-8"><Link href="/shop"><ShoppingBag className="size-4"/>Continue shopping</Link></Button></div>;
 if(lines.length===0)return <div className="mx-auto max-w-2xl px-6 py-24 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-muted text-muted-foreground"><ShoppingBag className="size-8"/></div><h1 className="mt-6 font-display text-4xl">Your cart is empty</h1><p className="mx-auto mt-4 max-w-md text-muted-foreground">You haven't added any pieces yet. Explore the collection and find something you love.</p><Button asChild className="mt-8"><Link href="/shop"><ShoppingBag className="size-4"/>Browse the collection</Link></Button></div>;
 const checkout=async()=>{setLoading(true);try{const s=await api.createCheckout(items.map(x=>({artworkId:x.artwork!.id,quantity:x.line.quantity})));window.location.href=s.url}catch(e){toast.error(e instanceof Error?e.message:"Checkout failed");setLoading(false)}};
 return <div className="mx-auto max-w-6xl px-6 py-12"><Link href="/shop" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4"/>Continue shopping</Link><div className="mt-6 flex items-end justify-between"><h1 className="font-display text-4xl">Your Cart</h1><span className="text-sm text-muted-foreground">{lines.reduce((s,i)=>s+i.quantity,0)} items</span></div><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_360px] lg:gap-12"><section>{isLoading?<div className="space-y-4"><Skeleton className="h-32"/><Skeleton className="h-32"/></div>:<ul className="space-y-4">{items.map(({line,artwork},index)=><li key={artwork!.id} className="flex gap-4 rounded-lg border bg-card p-4 shadow-subtle sm:gap-6 sm:p-5"><Link href={`/artwork/${artwork!.id}`} className="shrink-0 overflow-hidden rounded-md border"><img src={artwork!.imageUrl} alt={artwork!.title} className="h-24 w-20 object-cover sm:h-28 sm:w-24"/></Link><div className="flex min-w-0 flex-1 flex-col"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><Link href={`/artwork/${artwork!.id}`} className="truncate font-display text-lg font-medium">{artwork!.title}</Link><p className="mt-1 text-sm font-medium text-primary">{format(artwork!.price)}</p></div><Button variant="ghost" size="icon" onClick={()=>remove(artwork!.id)}><Trash2 className="size-4"/></Button></div><div className="mt-auto flex items-center justify-between pt-4"><div className="inline-flex items-center rounded-md border"><Button variant="ghost" size="icon" className="size-8" onClick={()=>update(artwork!.id,line.quantity-1)}><Minus className="size-4"/></Button><span className="w-10 text-center text-sm">{line.quantity}</span><Button variant="ghost" size="icon" className="size-8" onClick={()=>update(artwork!.id,line.quantity+1)}><Plus className="size-4"/></Button></div><p className="text-sm font-semibold">{format(artwork!.price*line.quantity)}</p></div></div></li>)}</ul>}</section><aside className="h-fit rounded-lg border bg-card p-6 shadow-subtle"><h2 className="font-display text-xl">Order summary</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Subtotal</dt><dd>{format(subtotal)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Shipping</dt><dd>Free</dd></div><div className="flex justify-between border-t pt-3"><dt>Total</dt><dd className="font-display text-xl text-primary">{format(subtotal)}</dd></div></dl><Button className="mt-6 w-full" size="lg" onClick={checkout} disabled={loading}>{loading?"Redirecting to payment…":"Checkout"}</Button><p className="mt-3 text-center text-xs text-muted-foreground">Secure payment processed by Stripe.</p></aside></div></div>
}
function format(c:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100)}
