"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import type { Artwork,Order } from "@/lib/types";
import { useArtworks,useDeleteArtwork,useOrders,useAddArtwork,useUpdateArtwork } from "@/hooks/useQueries";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { ImagePlus,Lock,LogOut,Pencil,ShieldAlert,Trash2 } from "lucide-react";
import { toast } from "sonner";

export default function AdminPage(){
 const router=useRouter();const{data:auth,isLoading:authLoading}=useAdmin();const{data:artworks=[],isLoading}=useArtworks();const{data:orders=[]}=useOrders();const del=useDeleteArtwork();const add=useAddArtwork();const update=useUpdateArtwork();
 const[login,setLogin]=useState("");const[editing,setEditing]=useState<Artwork|null>(null);const[showForm,setShowForm]=useState(false);const[analytics,setAnalytics]=useState<any>(null);
 useEffect(()=>{if(auth?.isAdmin)api.adminAnalytics().then(setAnalytics).catch(()=>{});},[auth?.isAdmin]);
 if(authLoading)return <div className="mx-auto max-w-6xl px-6 py-20">Loading admin…</div>;
 if(!auth?.isAdmin)return <div className="mx-auto flex max-w-md flex-col items-center px-6 py-24 text-center"><div className="flex size-14 items-center justify-center rounded-full bg-muted"><Lock className="size-6"/></div><h1 className="mt-6 font-display text-3xl">Admin Access</h1><p className="mt-3 text-muted-foreground">Sign in with the admin password configured in Vercel environment variables.</p><form className="mt-8 flex w-full gap-2" onSubmit={async e=>{e.preventDefault();try{await api.adminLogin(login);setLogin("");router.refresh()}catch{toast.error("Invalid password")}}}><Input type="password" value={login} onChange={e=>setLogin(e.target.value)} placeholder="Admin password"/><Button>Sign in</Button></form></div>;
 const save=async(input:{title:string;price:number;description:string;featured:boolean;file?:File})=>{try{if(editing)await update.mutateAsync({id:editing.id,input});else{if(!input.file)throw new Error("Image required");await add.mutateAsync({...input,file:input.file})}toast.success(editing?"Artwork updated":"Artwork added");setShowForm(false);setEditing(null)}catch(e){toast.error(e instanceof Error?e.message:"Something went wrong")}};
 return <div className="mx-auto max-w-6xl px-6 py-16"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-muted-foreground">Admin</p><h1 className="mt-3 font-display text-3xl">Gallery Management</h1><p className="mt-3 text-muted-foreground">Manage artworks, orders and store analytics.</p></div><div className="flex gap-2"><Button variant="outline" onClick={async()=>{await api.adminLogout();router.refresh()}}><LogOut className="size-4"/>Sign out</Button><Button onClick={()=>{setEditing(null);setShowForm(true)}}><ImagePlus className="size-4"/>Add artwork</Button></div></div>
 {analytics&&<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Visitors",analytics.visitors],["Paid orders",analytics.orders],["Revenue",format(analytics.revenue)],["Artworks",analytics.artworks]].map(([k,v])=><div key={String(k)} className="rounded-lg border bg-card p-5"><p className="text-sm text-muted-foreground">{k}</p><p className="mt-2 font-display text-2xl">{v}</p></div>)}</div>}
 <section className="mt-10"><h2 className="mb-4 font-display text-lg">Artworks</h2><div className="overflow-hidden rounded-lg border bg-card">{isLoading?<div className="p-6">Loading…</div>:artworks.length===0?<div className="p-10 text-center text-muted-foreground">No artworks yet.</div>:artworks.map((a,i)=><div key={a.id} className="flex items-center gap-4 border-b px-5 py-4 last:border-b-0"><img src={a.imageUrl} alt={a.title} className="size-16 shrink-0 rounded-md object-cover"/><div className="min-w-0 flex-1"><div className="flex gap-2"><h3 className="truncate font-display">{a.title}</h3>{a.featured&&<Badge>Featured</Badge>}</div><p className="truncate text-sm text-muted-foreground">{a.description||"No description"}</p></div><p className="font-semibold">{format(a.price)}</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>{setEditing(a);setShowForm(true)}}><Pencil className="size-4"/>Edit</Button><Button variant="ghost" size="sm" onClick={async()=>{if(confirm(`Delete "${a.title}"?`)){await del.mutateAsync(a.id);toast.success("Artwork deleted")}}}><Trash2 className="size-4"/></Button></div></div>)}</div></section>
 <section className="mt-12"><h2 className="mb-4 font-display text-lg">Customer orders</h2><div className="overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-4">Order</th><th className="p-4">Status</th><th className="p-4">Total</th><th className="p-4">Customer</th><th className="p-4">Date</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b last:border-0"><td className="p-4 font-medium">#{o.id}</td><td className="p-4"><Badge variant={o.status==="PAID"?"secondary":o.status==="FAILED"?"destructive":"outline"}>{o.status.toLowerCase()}</Badge></td><td className="p-4">{format(o.total)}</td><td className="p-4">{o.customerName||o.email||"Guest"}</td><td className="p-4 text-muted-foreground">{new Date(o.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{orders.length===0&&<div className="p-10 text-center text-muted-foreground">No orders yet.</div>}</div></section>
 {showForm&&<ArtworkForm artwork={editing} onCancel={()=>{setShowForm(false);setEditing(null)}} onSave={save}/>}
 </div>
}
function useAdmin(){const[state,setState]=useState<{isAdmin:boolean}|undefined>();const[loading,setLoading]=useState(true);useEffect(()=>{api.adminMe().then(setState).catch(()=>setState({isAdmin:false})).finally(()=>setLoading(false))},[]);return{data:state,isLoading:loading}}
function format(c:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100)}
function ArtworkForm({artwork,onCancel,onSave}:{artwork:Artwork|null;onCancel:()=>void;onSave:(x:{title:string;price:number;description:string;featured:boolean;file?:File})=>void}){const[title,setTitle]=useState(artwork?.title||"");const[price,setPrice]=useState(artwork?(artwork.price/100).toFixed(2):"");const[description,setDescription]=useState(artwork?.description||"");const[featured,setFeatured]=useState(artwork?.featured||false);const[file,setFile]=useState<File>();return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={e=>{e.preventDefault();if(!title.trim()||Number(price)<=0)return toast.error("Enter a title and valid price");onSave({title:title.trim(),price:Number(price),description:description.trim(),featured,file})}} className="w-full max-w-lg space-y-5 rounded-lg border bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-display text-xl">{artwork?"Edit artwork":"Add artwork"}</h2><Button type="button" variant="ghost" onClick={onCancel}>Close</Button></div><div><Label>Artwork image</Label>{file?<img src={URL.createObjectURL(file)} className="mt-2 aspect-[4/3] w-full rounded-md object-cover"/>:artwork?<img src={artwork.imageUrl} className="mt-2 aspect-[4/3] w-full rounded-md object-cover"/>:<label className="mt-2 flex aspect-[4/3] cursor-pointer items-center justify-center rounded-md border border-dashed bg-muted/40"><ImagePlus className="size-6"/><input type="file" accept="image/*" className="sr-only" onChange={e=>setFile(e.target.files?.[0])}/></label>}<input type="file" accept="image/*" className="mt-2 block text-sm" onChange={e=>setFile(e.target.files?.[0])}/></div><div><Label>Title</Label><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Midnight Study"/></div><div><Label>Price (USD)</Label><Input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></div><div><Label>Description</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/>Feature on home page</label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onCancel}>Cancel</Button><Button type="submit">{artwork?"Save changes":"Add artwork"}</Button></div></form></div>}
